<?php
declare(strict_types=1);

/**
 * Acquired.com Payments Integration for Magento2
 *
 * Copyright (c) 2024 Acquired Limited (https://acquired.com/)
 *
 * This file is open source under the MIT license.
 * Please see LICENSE file for more details.
 */
 
$info = $block->getInfo();
$order = $info->getOrder();
$payment = $order->getPayment();
$title = $payment->getMethodInstance()->getTitle();
?>

<p>Acquired Payments - <?= $title; ?></p>
<p><img width="50" height="30" src="<?= $this->getCardIcon((string)$payment->getCcType()); ?>" title="<?= $title; ?>" alt="<?= $payment->getCcType(); ?>"/></p>
<p>Last 4: **** <?= $this->getPaymentInformation($payment, 'cc_last4'); ?></p>