<?php
/**
 * Acquired Limited Payment module (https://acquired.com/)
 *
 * Copyright (c) 2023 Acquired.com (https://acquired.com/)
 * See LICENSE.txt for license details.
 */
?>

<?php /** @var \Magento\Framework\View\Element\Template $block */?>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        let responseData = <?php echo $block->getData('response_data'); ?>;
        window.parent.postMessage(responseData, '*');
    });
</script>
