<?php

/**
 * Acquired.com Payments Integration for Magento2
 *
 * Copyright (c) 2024 Acquired Limited (https://acquired.com/)
 *
 * This file is open source under the MIT license.
 * Please see LICENSE file for more details.
 */
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function(layout, $) {
        $(function() {
            var paymentMethodData = {
                method: "<?= \Acquired\Payments\Ui\Method\PayByBankProvider::CODE; ?>"
            };
            layout([{
                component: 'Acquired_Payments/js/view/payment/method-renderer/multishipping/pay-by-bank',
                name: 'payment_method_acquired_pay_by_bank',
                method: paymentMethodData.method,
                item: paymentMethodData
            }]);

            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->