<?php

declare(strict_types=1);

/**
 * Acquired Limited Payment module (https://acquired.com/)
 *
 * Copyright (c) 2024 Acquired.com (https://acquired.com/)
 * See LICENSE.txt for license details.
 */

$info = $block->getInfo();
$order = $info->getOrder();
$payment = $order->getPayment();
$title = $payment->getMethodInstance()->getTitle();
?>

<h4>
    <span class="acquired-title">Acquired Payments - <?= $title; ?></span>
    <?php if($payment->getMethod() == \Acquired\Payments\Ui\Method\CardProvider::CODE) : ?>
    <span class="acquired-card-icon"><img width="50" height="30" src="<?= $this->getCardIcon((string)$payment->getCcType()); ?>" title="<?= $title; ?>" alt="<?= $payment->getCcType(); ?>" /></span>
    <?php endif; ?>
</h4>

<table class="admin__table-secondary order-information-table payment-info">
    <tbody>
        <tr>
            <th><?php echo __('Transaction Id'); ?></th>
            <td class="acquired-value">
                <?= $payment->getLastTransId(); ?>
            </td>
        </tr>

        <?php if($payment->getMethod() == \Acquired\Payments\Ui\Method\CardProvider::CODE) : ?>
            <tr>
                <th><?php echo __('Transaction Type'); ?></th>
                <td class="acquired-value">
                    <?= $this->getPaymentInformation($payment, 'transaction_type'); ?>
                </td>
            </tr>
        <tr>
            <th><?php echo __('Last 4'); ?></th>
            <td class="acquired-value">
                <?= $this->getPaymentInformation($payment, 'cc_last4'); ?>
            </td>
        </tr>
        <tr>
            <th><?php echo __('Authorization Code'); ?></th>
            <td class="acquired-value">
                <?= $this->getPaymentInformation($payment, 'authorization_code'); ?>
            </td>
        </tr>
        <tr>
            <th><?php echo __('AVS Address'); ?></th>
            <td class="acquired-value">
                <?= $this->getPaymentInformation($payment, 'avs_address'); ?>
            </td>
        </tr>
        <tr>
            <th><?php echo __('AVS Postcode'); ?></th>
            <td class="acquired-value">
                <?= $this->getPaymentInformation($payment, 'avs_postcode'); ?>
            </td>
        </tr>
        <tr>
            <th><?php echo __('CVV'); ?></th>
            <td class="acquired-value">
                <?= $this->getPaymentInformation($payment, 'cvv'); ?>
            </td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>